### PR TITLE
Support Boost.Parameter-enabled function call operators, additional parameter categories, and perfect forwarding

### PR DESCRIPTION
**Pull request by CromwellEnage**
1.  Added code generation macros BOOST_PARAMETER_FUNCTION_CALL_OPERATOR and BOOST_PARAMETER_CONST_FUNCTION_CALL_OPERATOR to <boost/parameter/preprocessor.hpp>.  Both BOOST_PARAMETER_MEMBER_FUNCTION and BOOST_PARAMETER_CONST_MEMBER_FUNCTION concatenate the name parameter with other text to form internal name-ids as part of their expansions, so they cannot accept operator().  With the new macros, Boost.Parameter-enabled function call operators are now possible.  See "test/preprocessor_eval_cat_8.cpp" for example usage.

2.  Added parameter category qualifiers "consume", "move_from", and "forward" (current qualifiers are "in", "out", and "in_out") based on http://www.modernescpp.com/index.php/c-core-guidelines-how-to-pass-function-parameters. Added new usage syntax BOOST_PARAMETER_NAME((object-name), namespace-name) qualifier(tag-name)) and BOOST_PARAMETER_NAME(qualifier(name)).  (Existing code that uses qualifiers directly and correctly with BOOST_PARAMETER_FUNCTION and other code generation macros should remain unaffected for now, so no breaking changes.)  The reason for the change in usage is to enable applying of parameter category constraints to Boost.Parameter-enabled functions and constructors invoked through argument composition.  (Otherwise, it is currently possible to use argument composition to bypass parameter category constraints applied in BOOST_PARAMETER_FUNCTION et. al.)  See "test/compose.cpp" for example usage.

3.  The end of section 3.2.1 of the current home page tutorial notes "that because of the forwarding problem, parameter::parameters::operator() can't accept non-const rvalues."  Added code to eliminate this problem.  As a positive side effect, Boost.Parameter-enabled functions and constructors are no longer bound by BOOST_PARAMETER_MAX_ARITY on compilers that support perfect forwarding.  User code can now check for this support by detecting the configuration macro BOOST_PARAMETER_HAS_PERFECT_FORWARDING, or manually turn off this support by defining the configuration macro BOOST_PARAMETER_DISABLE_PERFECT_FORWARDING.  See "test/evaluate_category.cpp" and "test/preprocessor_eval_category.cpp" for example usage.

4.  Keyword templates generated by BOOST_PARAMETER_TEMPLATE_KEYWORD can now accept function types.  See "test/function_type_tpl_params.cpp" for example usage.

5.  It is no longer necessary to wrap boost::ref() around non-const lvalues, although this feature is still supported, and std::ref() is now also an option.  See "test/compose.cpp" and "test/evaluate_category.cpp".

6.  Updated documentation to reflect the above changes.

### CODE REVIEW

**Comment by eldiener** [comment]
Would you be interested in becoming the maintainer for Boost Parameter if you feel you are qualified to do so ? Currently there is really no maintainer as the original developers are no longer active in Boost. You could more easily bounce your ideas for improving Boost Parameter, as given in this PR, off other Boost developers on the developers mailing list if you were a maintainer for the library. You also seem very knowledgable in the internals of how Boost parameter does work and in the use of the library.

**Comment by CromwellEnage** [comment]
Edward Diener wrote:
> Would you be interested in becoming the maintainer for Boost Parameter if
you feel you are qualified to do so?
Certainly.  How shall I proceed?

Cromwell D. Enage

**Comment by eldiener** [comment]
Introduce yourself on the Boost mailing list as someone who would like to help with Boost and say that you would like to be a maintainer of the Boost Parameter library. You should explain anything you like about your interest and your plan to make Boost Parameter better. From there you should get some feedback from others and hopefully someone from the Boost Steering Committee will chime in and if it is felt that you are knowledgable, will offer you the ability to maintain Boost Parameter and have write access to the Boost Parameter repository. The main interest of most maintainers is usually fixing bugs and handling PRs but there is theroretically nothing which prevents a maintainer from improving a library. The important thing is to discuss ideas and changes with other developers on the Boost developers mailing list. Since Boost has far more libraries than active maintainers new people who want to maintain or help to maintain a library are welcome as long as they have the necessary C++ expertise to do so.

**Comment by pdimov** [comment]
This represents an impressive amount of work, and the changes look sensible and would improve the library.

However, it might be more manageable and more convenient for @eldiener to evaluate and merge them if they are broken up into multiple pull requests, one per feature. The changes seem logically separate.

PS Sorry for introducing a merge conflict, I updated .travis.yml to get a clearer picture of the health of the library at the moment, without noticing that this PR already has an expanded .travis.yml.

**Comment by CromwellEnage** [comment]
I would definitely like to introduce the improvements separately, but the current code structure prevents me from doing so in one shot.  Therefore, I plan to first submit pull requests for a more modular but functionally identical code structure.  For example, boost/parameter/preprocessor.hpp defines most of the macros that I need to modify, so I should move them to separate header files in such a way that I can work on the macros separately for the subsequent pull requests in which I'll introduce the actual features.  The same will go for boost/parameter/parameters.hpp and any other monolithic header files.  Only after the restructuring is implemented, approved, and merged will I submit the pull requests implementing the new features.  The one exception is the improvement to BOOST_PARAMETER_TEMPLATE_KEYWORD, which I may be able to submit a separate PR for as-is.

If you approve of this plan, then I will go ahead and close this PR.

**Comment by pdimov** [comment]
The plan sounds good to me. Let's see what @eldiener thinks.

**Comment by eldiener** [comment]
I am good with an incremental approach to changes. Most important is that any change which might affect end-users needs to be documented and that any change should test correctly. I have been just one of the many caretakers of Parameter but I am encouraged by someone like Mr. Enage who wants to improve and modernize the library, which is why I supported him as a possible maintainer of Parameter. It is a complicated but very useful library and it needs someone who understands the internals of its design and seeks to improve it.

**Comment by pdimov** [comment]
Mr. Enage seems more than qualified for the position of a maintainer, but let us get some commits of his into the revision history first. :-)

**Comment by eldiener** [comment]
I concur. I will review/test any PR he submits.

**Pull request closed without merging**
