### PR TITLE
 Fix Issue #31, Issue #32, Issue #33

### PR DESCRIPTION
**Pull request by CromwellEnage**
- Change test/evaluate_category.cpp and test/preprocessor_eval_category.cpp so that the tests pass for msvc-8.0, msvc-9.0, msvc-10.0, and msvc-11.0.
- Change test/Jamfile.v2 so that the compose_msvc11_fail_11 test runs only for msvc-11.0.
- Ensure that file permissions for header and source files do not include execute.
- Also, use the parameter_all_tests_cxx03 test suite vice the parameter_all_tests test suite when CXXSTD=03.

### CODE REVIEW

**Comment by eldiener** [comment]
Your jamfile change is saying that a number of aliases which have 'msvc' as part of their names should be run by all compilers. Is that what you intend ? In that case renaming the aliases without the 'msvc' part seems clearer.

**Comment by CromwellEnage** [comment]
Okay, I’ll rename the aliases to make their purpose more clear.

**Comment by eldiener** [comment]
You are missing the point. Tests in the jamfile are often run as just 'b2 toolset=xxx' without specifying an alias name. In fact that is how the tests are run in the Boost regression test framework and how I run the tests locally. This has to work for all compilers. I understand that your CI tests run specific to certain aliases for certain tests, but that is not the canonical way of running the tests for regression testing or local testing.

The tests you now specify as msvc12 etc. will be run when I use 'b2 toolset=gcc-8.1'. They need to pass no matter what compiler I use, since you removed the msvc requirement on those tests. Therefore naming them msvc12, or even msvcxxx is a misleading name for them. It does not bother me if you want to keep those names, just as long as those tests run correctly for all compilers.

**Comment by CromwellEnage** [comment]
Ah, that's what you meant.  Okay, I'll try to rearrange the aliases and reinstate the msvc requirements so that .travis.yml and appveyor.yml won't need to specify an alias name.  I'll bring back test-suite statements if I have to.

**Comment by eldiener** [comment]
You can continue to use alias names for travis and appveyor. I am just saying that regression testing and normal local testing does not use alias names. However there is nothing wrong with invoking tests using alias names itself. In the doc you can explain the various testing procedures which can be used with alias names. But you still need to have the jamfile work correctly when no alias names are used.

**Comment by eldiener** [comment]
I also wanted to mention that if you specify 'explicit somealias ;' in a jamfile, then that alias does not get processed when you run b2 against the jamfile specifying no alias names; otherwise all aliases get processed when specifying no alias names. You might want to use that technique in your design of the Parameter test jamfile.

**Comment by CromwellEnage** [comment]
I've rearranged most of the aliases so they're still useful.  Nevertheless, I brought back the test-suite statement, so I don't think I need 'explicit [some_alias]'.  (Thanks for the tip, though.)

**Comment by eldiener** [comment]
Why did you remove the jamfile code which specifies that the python test fails for gcc on Windows ?

**Comment by CromwellEnage** [comment]
Because they did’t fail when address-model was set to 32 bits.  But if
mingw compiler configurations are expected to fail on python tests
regardless of address-model, then I’ll put that back.

**Comment by eldiener** [comment]
My testing show that there is failure when the address model is set to 32-bits and the mode is c++11 on up; only when the mode is c++03 mode does it succeed. But since c++03 mode will hardly be used by programmers I would rather we just say that it always fails with gcc under Windows. This is not the fault of your code but is the fault instead of a low-level Python header. See https://github.com/boostorg/python/issues/140 and https://github.com/python/cpython/pull/880.

**Comment by eldiener** [comment]
When you have more than one test of the same name, such as 'evaluate_category.cpp' they need a different final name to distinguish them. The default final name, if you do not choose to give one, is the test name minus the extension, so that the default final name for 'evaluate_category.cpp'  is 'evaluate_category'  but you can always of course specify the final name you want. But if you have more than one of the same final names, even if they are in different aliases, you will get the error:

error: No best alternative for ./evaluate_category_msvc_fail
    next alternative: required properties: (empty)
        matched
    next alternative: required properties: (empty)
        matched

etc. The same thing goes for preprocessor_eval_category.cpp in your jamfile. So you need to correct this in your jamfile.v2 file.

**Comment by CromwellEnage** [comment]
I noticed that the error shows up even for targets without any tests.  What should I do about those?

**Comment by eldiener** [comment]
Please givew me an example of the error showing for targets without any tests ?

**Comment by CromwellEnage** [comment]
For Job 3 (g++-4.7), the first error reads:

error: No best alternative for ./parameter_macros_eval_category
    next alternative: required properties: <target-os>linux <toolset>gcc
        matched
    next alternative: required properties: <cxxstd>03 <target-os>darwin
        not matched
    next alternative: required properties: <target-os>windows <toolset>gcc
        not matched
    next alternative: required properties: <cxxstd>98
        not matched
    next alternative: required properties: <cxxstd>03
        matched

The job ends up picking the first alternative in this case, which is the desired outcome here.

**Comment by CromwellEnage** [comment]
Okay, I figured it out, at least for gcc.  I didn't find any Jamfile errors in the test results off my fork.

**Comment by eldiener** [comment]
Yes <version> is really not a separate property. It needs to always be <toolset-somecompiler:version>nnn. I am glad you figured that out.

**Pull request merged**
