### PR TITLE
Supressed 'unused parameters' warnings.

### PR DESCRIPTION
**Pull request by povilasb**

### CODE REVIEW

**Comment by eldiener** [comment]
You should not be making PRs on the 'master' branch. If the fix is already in 'develop' it will get into 'master' when 'develop' is merged to 'master'.

**Comment by eldiener** [comment]
My error. I see where the 'develop' and the 'master' branch have not been synced for a long time so I understand why this PR was made.

**Comment by eldiener** [comment]
I manually merged the "suppress 'unused parameter' warning/error" portion of your PR. The removing of trailing white spaces is not necessary for correct C++ compilation.

**Comment by povilasb** [comment]
Well trailing white space removal is for code neatness. They are totally redundant :)

**Pull request closed without merging**
