### PR TITLE
Fix multi-line comment

### PR DESCRIPTION
**Pull request by CromwellEnage**

### CODE REVIEW

**Comment by CromwellEnage** [comment]
To elaborate, some tests in other libraries (e.g. Boost.Graph) are emitting the following warning.

../../../boost/parameter/aux_/tagged_argument.hpp:643:1: warning: multi-line comment [-Wcomment]

This PR aims to eliminate the warning.

**Comment by eldiener** [comment]
I do not understand your fix.

**Comment by CromwellEnage** [comment]
The original fix was meant to eliminate warnings about multi-line comments that were showing up in tests for other libraries, such as Boost.Graph.  In retrospect, however, I should have kept it simple in the first place with this fix I just submitted.

**Comment by eldiener** [comment]
Your original fix was wrong AFAIK. Placing a continuation character after a single line comment does nothing.

The updated fix works although the original warning is perplexing. Why have a compiler warning when you have two consecutive single line comments ? BTW if you wanted to keep the comment but avoid the warning you could have changed it to:

```
/* #if !defined(BOOST_NO_FUNCTION_TEMPLATE_ORDERING) && \
      !BOOST_WORKAROUND(__BORLANDC__, BOOST_TESTED_AT(0x564)) */
```

**Comment by CromwellEnage** [comment]
I'll keep the C-style comment suggestion in mind for next time.  Thanks!

**Pull request merged**
